### ISSUE TITLE
Assign the player into a category

### ISSUE THREAD

**Issue by ottotsuma** [KumaV1/Custom-Modifiers-in-Melvor#16]
So something like the player during a quest "becomes" undead. We would assign the category "undead" to the player and they would take the extra damage etc normal undead would. 

This might be very Niche :D

**Comment by KumaV1** [comment]
How do your "quests" work exactly? Because, if you have a look at the main page, you can see modifiers saying "Marks the affected as X". Which makes them affected to modifiers such as "Increased damage against Undead".
```js
// Btw, "isHuman" is applied at the start of battle, based on whether they are inherintly typed as e.g. human, 
// cause checking a boolean is quicker than checking arrays whenever calculation has to take place
if (entity.target.isHuman || entity.target.modifiers.humanTraitApplied > 0) {
    modification += entity.modifiers.increasedDamageReductionAgainstHumans - entity.modifiers.decreasedDamageReductionAgainstHumans;
}
```

If your quest uses a custom slayer area, you could set that as the area effect, granted it doesn't work well with the description I reckon, especially if you don't want any form of "Flat Slayer Area Effect Reduction" to immediately dispel it.

Alternatively, you could give monsters a special attack which applies said trait for some time.

With all that being said, there are two things I can improve upon actually, which I would do once the dynamic typing is finished:
* Provide a "StackingEffect" for each type, which would also appear in the "Creator Toolkit" Data Creator, making adding it easier to use, than constantly having to configure "Custom" effects, which as of now do not actually display custom modifiers in the Creator Toolkit
  * Granted, in order for them to appear in the Creator Toolkit, I basically have to build small "GameData" packages dynamically, though it's certainly possible
* Provide "On spawn, Increased/Decreased chance to apply {TYPE/TRAIT} to the enemy until the end of battle" modifiers, which could be set on the monster, so it applies said trait to the player

What do you think of those?

**Comment by KumaV1** [comment]
Created [this issue](https://github.com/KumaV1/Custom-Modifiers-in-Melvor/issues/17), based on the latter part of the last comment. With that, this issue is presumably redundant

**Comment by ottotsuma** [comment]
Sorry for the slow reply, you know why ^^ 

The function above will be fine for combat, I think that will cover most instances but it'll be triggering a lot If I want the player to be a monster type permanently. 

I think 

`Provide "On spawn, Increased/Decreased chance to apply {TYPE/TRAIT} to the enemy until the end of battle" modifiers, which could be set on the monster, so it applies said trait to the player`

This would be ideal for the combat situation, my thoughts where that when a player buys something from the shop it would apply that typing to him, and from then on all monsters and items would have effects against that typing would effect the player. I am thinking I can achieve this from inside my mod though, possibly. 

I'll give it a try after your update to types on this mod and I'll let you know if I can make the player an undead. I was thinking they would become a vampire if they are bitten by one, become weak to undead damage and have to go about solving that issue.

**Comment by ottotsuma** [comment]
Maybe I can achieve it by having a game.playerMonsterType = "Human", change to undead or something. Then checking that in the combat damage function, patching in the damage, or having the monster give the player the new type or something.

**Comment by KumaV1** [comment]
Hey, the mentioned "Effect on spawn" will, in the background, simply set a certain modifier. So any logic based on typing should generally check both of those values, either one will by itself then cause the entity to be treated as said type.
```js
if (entity.target.isUndead || entity.target.modifiers.undeadTraitApplied > 0) {
    // Check both the organic type allocation and artificial type/trait allocation to do whatever you want to do
}

// In your case, if outside of combat, the former check would basically be irrelevant and instead look something like this.
if (game.combat.player.modifiers.undeadTraitApplied > 0) {
    // Check both the organic type allocation and artificial type/trait allocation to do whatever you want to do
}
``` For outside of battle, you can then increase that modifier as you would any other, be it through items or a shop purchase. Although with a shop purchase, they would basically become undead permanently, both inside and outside of combat - unless you offer another shop purchase to reduce said modifier again. So depending on how exactly you are envisioning player type allocation, the existing modifier may or may not have to resort to implementing something yourself.

On that note, the Monster-Type-Overview should probably have a "Current trait on player" section applied to them, so they can have an idea what they currently are inherintly, because shop-upgrades are harder to keep track of/check in general than the items you have equipped
